In [1]:
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
iris = datasets.load_iris()
iris_x = iris.data
#将数据集传递为数组形式
iris_y = iris.target
#将数据集中的每个标签(index)传递为数组形式

In [4]:
indices = np.random.permutation(len(iris_x))
#利用permutation方法将数据打乱

In [5]:
iris_x_train = iris_x[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
#取训练数据集

In [6]:
iris_x_test = iris_x[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]
#取测试数据集

In [7]:
knn = KNeighborsClassifier()
knn.fit(iris_x_train,iris_y_train)

KNeighborsClassifier()

In [8]:
iris_y_predict = knn.predict(iris_x_test)

In [9]:
probility = knn.predict_proba(iris_x_test)
#计算各测试数据集基于概率的预测

In [10]:
score=knn.score(iris_x_test,iris_y_test,sample_weight=None)
#计算预测的准确率

In [11]:
print('iris_y_predict = ')  
print(iris_y_predict) 
#输出预测的结果

iris_y_predict = 
[1 2 1 0 0 0 2 1 2 0]


In [12]:
print('iris_y_test = ')
print(iris_y_test) 
#输出测试的结果，与预测结果比较

iris_y_test = 
[1 1 1 0 0 0 2 1 2 0]


In [14]:
print('Accuracy:',score)
#输出准确率

Accuracy: 0.9


In [13]:
print ('probility:',probility)

probility: [[0.  1.  0. ]
 [0.  0.4 0.6]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]]
